### PR TITLE
Update the README.md file to describe the repo.

### PR DESCRIPTION
**Pull request by yiichoong**
Modify the contains of the file base on the instruction given on the "Week 0 - Setup".

### CODE REVIEW

**Review by ngkelly3 — APPROVED** [review]
🎉

**Comment by ngkelly3** [comment]
Hey Yii Choong, just checking in that you’re not waiting on anything for me here? Everything looks good on my end, feel free to merge the pull request when you’re ready 🚢

**Comment by yiichoong** [comment]
I'm good, sorry for keeping you waiting. I already sent the request.

**Comment by ngkelly3** [comment]
> I'm good, sorry for keeping you waiting. I already sent the request.
> […](#)

Oh no problem at all, just wanted to make sure I didn't miss anything. Thanks for the reply!

**Pull request merged**
